service: serverless-example
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  hellofunction:
    handler: hello.handler
    events:
      - httpApi:
          path: /hello
          method: get
